"""alter tenant timestamps to with timezone

Revision ID: bf05f624cb08
Revises: 60e7e15e4cfe
Create Date: 2026-09-30 22:58:52.248293

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf05f624cb08'
down_revision: Union[str, Sequence[str], None] = '60e7e15e4cfe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
