"""alter tenant timestamps to with timezone

Revision ID: e2c568bc28d6
Revises: cf3a0f3151fe
Create Date: 2026-09-30 22:27:50.577961

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2c568bc28d6'
down_revision: Union[str, Sequence[str], None] = 'cf3a0f3151fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
